name: graduationproject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  font_awesome_flutter: ^11.0.0
  dio: ^5.9.2
  country_picker: ^2.0.27
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  equatable: ^2.0.8
  icons_plus: ^5.0.0
  curved_navigation_bar: ^1.0.6
  flutter_localizations:
    sdk: flutter
  intl_phone_field: ^3.2.0
  flutter_svg: ^2.2.4
  fl_chart: ^1.2.0
  file_picker: ^8.1.5
  image_picker: ^1.2.1
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  google_sign_in: ^6.2.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/company/Onboarding/
    - assets/company/logo/
    - assets/company/icon/
    - assets/company/forget/
    - assets/company/profile/
